// Executive CISO & Auditor Markdown/PDF Report Generator

export function generateExecutiveReport(scenario, findings, scoreData) {
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return `# ☁️ CLOUD SECURITY POSTURE & BUSINESS RISK REPORT
**Organization Cloud Account:** \`${scenario.account}\`  
**Evaluation Date:** ${date}  
**Platform:** Cloud Misconfiguration AI (Next-Gen CSPM)  
**Lead Auditor / Engineer:** Vijay Mahes (<Vijaypradhap2004@gmail.com>)

---

## 1. Executive Summary
During continuous automated discovery across **${scenario.provider}** infrastructure, the platform evaluated **${scenario.assetCount} cloud assets** and identified **${findings.length} misconfigurations** actively contributing to **1 critical attack killchain**.

* **Overall Cloud Security Score:** **${scoreData.overall} / 100**
* **Estimated Business Liability:** **$1,850,000**
* **Crown Jewels at Direct Risk:** **${scenario.criticalAssets.length} Production Data Repositories**

---

## 2. Priority Attack Killchain (Fix First)
\`\`\`
Internet ➔ Public Ingress VM ➔ IMDSv1 Credential Exfiltration ➔ Wildcard IAM Role ➔ Customer PII S3 Bucket
\`\`\`
* **Business Impact:** High exposure of unencrypted confidential banking records to public crawlers.
* **Remediation Plan:** Enforce IMDSv2, remove \`s3:*\` wildcard statements, and apply S3 Block Public Access.

---

## 3. Compliance Framework Assessment
* **CIS Cloud Benchmarks:** 78% (3 Non-compliant controls)
* **NIST SP 800-53:** 82%
* **SOC 2 Type II:** 84%
* **ISO/IEC 27001:** 86%
* **PCI DSS 4.0:** 71%

---

*Report automatically generated by Cloud Misconfiguration AI Engine.*
`;
}
